import type { Review } from '../types';

export const DEMO_REVIEWS: Review[] = [
  {
    id: 1,
    productId: 1,
    rating: 5,
    reviewText: "I bought this at 1am after she left and I had no idea what to text. Honestly thought it was another 'no contact' thing I'd quit after chapter two. I finished it in a night. The part about perceived value hit me hard — I stopped sending paragraphs and just... went quiet. Three weeks later she reached out. I'm not saying it's magic, but it gave me a plan when I had none.",
    displayName: 'Jake R.',
    name: 'Jake R.',
    approved: true,
    helpful: 23,
    createdAt: '2024-11-12T10:00:00Z',
  },
  {
    id: 2,
    productId: 1,
    rating: 5,
    reviewText: "Usually these ebooks read like a blog post stretched into 80 pages. This one doesn't. It's dense, a little cold even, but in a good way. Like someone finally explained the game without pretending love is Disney. I keep going back to the chapter on withdrawal dynamics.",
    displayName: 'Maya T.',
    name: 'Maya T.',
    approved: true,
    helpful: 18,
    createdAt: '2024-10-28T14:30:00Z',
  },
  {
    id: 3,
    productId: 1,
    rating: 5,
    reviewText: "My friend sent me the link and I rolled my eyes. Another $39 relationship guide? But I was stuck, so I got it. Best impulse buy of the year. The framework isn't about manipulation — it's about stopping self-sabotage. I finally understood why silence works, and it wasn't for the reason I thought.",
    displayName: 'Alex K.',
    name: 'Alex K.',
    approved: true,
    helpful: 31,
    createdAt: '2024-12-03T09:15:00Z',
  },
  {
    id: 4,
    productId: 1,
    rating: 4,
    reviewText: "The writing is premium. No filler, no 'you go girl' energy, just psychology. My only nitpick is I wanted more examples on what to actually say when they come back. Still, the clarity alone was worth the price. I felt less desperate after reading it, which is saying something.",
    displayName: 'Sarah L.',
    name: 'Sarah L.',
    approved: true,
    helpful: 12,
    createdAt: '2024-09-19T16:45:00Z',
  },
  {
    id: 5,
    productId: 1,
    rating: 5,
    reviewText: "I'm a therapist and I don't say this lightly: this is the only breakup resource I've recommended to clients that doesn't insult their intelligence. The attachment framing is accurate, the behavioral angle is practical, and it respects the reader's autonomy.",
    displayName: 'Dr. D. Patel',
    name: 'Dr. D. Patel',
    approved: true,
    helpful: 27,
    createdAt: '2024-11-05T11:20:00Z',
  },
  {
    id: 6,
    productId: 1,
    rating: 5,
    reviewText: "I didn't get my ex back. And weirdly, I'm okay with that now. The book made me realize I was chasing validation, not a relationship. Six months later I'm dating someone who actually puts in effort. I credit the mindset shift from this more than any advice my friends gave me.",
    displayName: 'Ryan H.',
    name: 'Ryan H.',
    approved: true,
    helpful: 15,
    createdAt: '2024-10-10T08:50:00Z',
  },
];
